layout:
  ortho_layout: {split: true, rows: 3, columns: 5, thumbs: 2, drop_pinky: true, drop_inner: true}
layers:
  default: [Q, W, F, P, B, J, L, U, Y, Z, A, R, S, T, G, M, N, E, I, O, V, C, D, H, K, X, nav, SPC, RSFT, sym]
  nav:
  - TAB
  - SWITCH APP
  - PREV TAB
  - NEXT TAB
  - NEW TAB
  - {t: LEFT, h: mouse}
  - {t: UP, h: mouse}
  - {t: DOWN, h: mouse}
  - {t: RIGHT, h: mouse}
  - BSPC
  - {t: LCTL, h: sticky}
  - {t: LALT, h: sticky}
  - {t: LGUI, h: sticky}
  - {t: LSFT, h: sticky}
  - SWITCH WIN
  - LEFT
  - DOWN
  - UP
  - RIGHT
  - ENTER
  - prev space
  - VOL DN
  - VOL UP
  - cmdk
  - ''
  - ''
  - ''
  - ''
  - lclk
  - num
  sym:
  - ESC
  - <
  - '>'
  - ':'
  - '~'
  - ^
  - ','
  - .
  - ''''
  - '`'
  - '-'
  - '*'
  - '='
  - _
  - $
  - '#'
  - {t: RSFT, h: sticky}
  - {t: RGUI, h: sticky}
  - {t: RALT, h: sticky}
  - {t: RCTL, h: sticky}
  - '|'
  - '@'
  - /
  - '!'
  - '&'
  - '?'
  - num
  - ''
  - ''
  - ''
  num:
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '0'
  - {t: LCTL, h: sticky}
  - {t: LALT, h: sticky}
  - {t: LGUI, h: sticky}
  - {t: LSFT, h: sticky}
  - ''
  - ''
  - {t: RSFT, h: sticky}
  - {t: RGUI, h: sticky}
  - {t: RALT, h: sticky}
  - {t: RCTL, h: sticky}
  - BT 1
  - BT 2
  - BT 3
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
combos:
- p: [16, 23]
  k: ;
  l: [default]
- p: [1, 11]
  k: '['
  l: [default]
- p: [2, 12]
  k: '{'
  l: [default]
- p: [3, 13]
  k: (
  l: [default]
- p: [8, 18]
  k: ']'
  l: [default]
- p: [7, 17]
  k: '}'
  l: [default]
- p: [6, 16]
  k: )
  l: [default]
- p: [2, 12]
  k: first tab
  l: [nav]
- p: [3, 13]
  k: last tab
  l: [nav]
- p: [4, 14]
  k: NEW WIN
  l: [nav]
- p: [8, 18]
  k: '"'
  l: [sym]
- p: [12, 21]
  k: +
  l: [sym]
- p: [13, 22]
  k: \
  l: [sym]
- p: [11, 20]
  k: '%'
  l: [sym]
- p: [0, 10]
  k: BT 0
  l: [num]
- p: [23, 24]
  k: BT CLR
  l: [num]
