manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: nickconway
      url-base: https://github.com/nickconway
  projects:
    - name: zmk
      remote: nickconway
      revision: dev
      import: app/west.yml
    - name: technikable-zmk-config
      remote: petejohanson
      revision: main
  self:
    path: config
