manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: rollow
      url-base: https://github.com/barbellboards
  projects:
    - name: Rollow-ZMK
      remote: rollow
      revision: barbellboards/rollow
      import: app/west.yml
  self:
    path: config
